modLoader="javafml"
loaderVersion="[28,)" #mandatory (28 is current forge version)
issueTrackerURL="https://github.com/sanman00/ExplosivePotions/issues"
# A list of mods - how many allowed here is determined by the individual mod loader
[[mods]]
modId="expotions"
version="${version}"
displayName="Explosive Potions"
#updateJSONURL="http://myurl.me/"
#logoFile="examplemod.png" # (in the root of the mod JAR)
authors="sanman00"
description='''
This mod adds explosive potions to Minecraft which can be brewed!
'''
